name: Build and Publish Docker image

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from GitHub ref
        id: extract_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Strip "refs/tags/" prefix from tag
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            # If not a tag (e.g. manual workflow dispatch), use "latest" only
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            faultoverload/showsweep:latest
            ${{ steps.extract_version.outputs.VERSION != 'latest' && format('faultoverload/showsweep:{0}', steps.extract_version.outputs.VERSION) || '' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
