name: Create Release on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git fetch --prune --unshallow

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump version (example: patch)
        id: bump_version
        run: |
          old_tag=${{ steps.get_tag.outputs.latest_tag }}
          old_version=$(echo "$old_tag" | sed 's/v//')
          IFS='.' read -ra parts <<< "$old_version"
          patch=$((parts[2]+1))
          new_version="v${parts[0]}.${parts[1]}.$patch"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          name: Release ${{ steps.bump_version.outputs.new_version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
